name: 编译爬虫
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'tvjar'
    - name: 安装JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: 开始编译
      run: ./buildAndGenJar.bat ec
    - name: 提交jar包
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'update spider jar'
        
    - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1