# File: .github/workflows/repo-sync.yml
name: 自动同步
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: repo-sync
jobs:
  repo-sync:
    name: 创建脚本
    runs-on: ubuntu-latest
    steps:
      - name: 设置githup信息
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
      - name: 设置SSH私钥信息
        env:
          MY_SCRIPTS_REPO_URL: github.com
          MY_SCRIPTS: my_scripts
          MY_SCRIPTS_HOST: jd_scripts_githup
          MY_SCRIPTS_KEY: ${{ secrets.token_Private_Keys }}
        run: |
          mkdir -p ~/.ssh/ && chmod 700 ~/.ssh
          echo "$MY_SCRIPTS_KEY" > ~/.ssh/$MY_SCRIPTS
          chmod 600 ~/.ssh/$MY_SCRIPTS
          echo -e "\n" >> ~/.ssh/config
          echo -e "Host $MY_SCRIPTS_HOST" >> ~/.ssh/config
          echo -e "\tHostname $MY_SCRIPTS_REPO_URL" >> ~/.ssh/config
          echo -e "\tIdentityFile=~/.ssh/$MY_SCRIPTS" >> ~/.ssh/config
          # echo -e "\n\nHost *\n StrictHostKeyChecking no\n" >> /etc/ssh/ssh_config
          chmod 644 ~/.ssh/config
          ssh-keyscan $MY_SCRIPTS_REPO_URL >> ~/.ssh/known_hosts
      - name: 开始同步
        run: |
          shopt -s extglob
          git clone https://github.com/once666/mysoft.git soft
          cd soft
          rm -rf .git
          rm -rf .github
          rm -rf .gitignore

          cd ../
          git clone -b my_soft git@jd_scripts_githup:ronghuaxueleng/my_tv_soft.git my_soft
          cp -rf ./soft/* ./my_soft
          cd ./my_soft
          git add .
          git commit --allow-empty -m "up"
          git push

          cd ../
          git clone https://github.com/FongMi/CatVodSpider.git CatVodSpider
          cd CatVodSpider
          rm -rf .git
          rm -rf .github
          rm -rf .gitignore

          cd ../
          git clone -b CatVodSpider git@jd_scripts_githup:ronghuaxueleng/my_tv_soft.git my_CatVodSpider
          cp -rf ./CatVodSpider/* ./my_CatVodSpider
          cd ./my_CatVodSpider
          git add .
          git commit --allow-empty -m "up"
          git push

      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1
